from .CreatePatientAccountQuery import CreatePatientAccountQuery
from .CreateDoctorAccountQuery import CreateDoctorAccountQuery
from .LoginQuery import LoginQuery
from .LogoutQuery import LogoutQuery
from .ResetPasswordQuery import ResetPasswordQuery
from .GetNewAccessTokenQuery import GetNewAccessTokenQuery